export const INVOICE_FETCH_INITIATED = 'INVOICE_FETCH_INITIATED';
export const INVOICE_FETCH_SUCCESS = 'INVOICE_FETCH_SUCCESS';
export const INVOICE_FETCH_FAILED = 'INVOICE_FETCH_FAILED';
export const PAGE_NUMBER = 'PAGE_NUMBER';
export const ROW_SELECTED_COUNT = 'ROW_SELECTED_COUNT';
export const FETCH_MORE_INVOICES_START = 'FETCH_MORE_INVOICES_START';
